{% set name = "pdf-reader" %}
{% set version = "2.15.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
    sha256: 18c6a986a84a3117fa49f4279fc2de51f5d2399b71833df5d2bccd595c7068ce

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -N -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}
    - rb-afm >=0.2.1,<2
    - rb-ascii85 >=1.0,<3.0,!=2.0.0
    - rb-hashery >=2.0,<3.0
    - rb-ruby-rc4 >=0
    - rb-ttfunk >=0

test:
  commands:
    - ruby -r pdf/reader -e 'exit 0'

about:
  home: https://github.com/yob/pdf-reader
  license: MIT
  license_family: MIT
  license_file:
    - MIT-LICENSE
  summary: |
    The PDF::Reader library implements a PDF parser conforming as much as possible to the PDF specification from Adobe
  description:
  doc_url: https://www.rubydoc.info/gems/pdf-reader
  dev_url: https://github.com/yob/pdf-reader

extra:
  recipe-maintainers:
    - jdmarques
    - rudispr
